### ISSUE TITLE
use #uuids as ids

### ISSUE THREAD

**Issue by behrica** [scicloj/metamorph#1]
https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/metamorph.20keyword.20as.20mode.20.3F

**Comment by genmeblog** [comment]
This requires a change here: https://github.com/scicloj/metamorph/blob/master/src/scicloj/metamorph/core.clj#L6

To get random uuid, call `(java.util.UUID/randomUUID)`

**Comment by behrica** [comment]
Closed in 0cdf49d50d81a19e2591dd8756327c34909e7566
